### ISSUE TITLE
not turing complete

### ISSUE THREAD

**Issue by Picatout** [carlini/printf-tac-toe#1]
You printf() program is not Turing complete as it require an external while() loop to work. It would be turing complete if this control structure was embedded inside the printf() arguments.

**Comment by carlini** [comment]
Yeah, technically you are correct.

We note this in our paper that I based this idea off of: "To achieve full Turing-complete computation, we need a way to loop a format string. This is possible by over-writing the pointer inside `printf()` that tracks which character in the format string is currently being executed. The attacker is unlucky in that at the time the "%n" format specifier is used, this value is saved in a register on our 64-bit system. However, we identify one point in time in which the attacker can always mount the attack. The `printf()` function makes calls to puts() for the static components of the string. When this function call is made, all registers are saved to the stack. It turns out that an attacker can overwrite this pointer from within the puts() function. By doing this, the format string can be looped."  (Taken from Section 6.2.1 of [this paper](https://www.usenix.org/system/files/conference/usenixsecurity15/sec15-paper-carlini.pdf).)

The problem with this in practice is it's not standards compliant, and system-dependent. I wrote this entry for IOCCC which prefers both, so used a loop to make it easier.

This doesn't bother me too much anyway. Real Turing completeness requires an infinite memory. So no C program on any computer is Turing complete either. It's all degrees of correctness.

**Comment by konstantinua00** [comment]
false advertisement
it's not "in a single call" :/

**Comment by dtwilliamson** [comment]
The `while...printf` is the "clock" of the Turing machine, not its program. The program (and data) is contained in `fmt` and `arg`. "A single call to printf" might be better stated as "A single printf statement".
